apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-claim
  namespace: project-ns
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi